---
version: '3'
services:
   barman:
        image: centos7/postgres:${TAG}
        container_name: barman
        hostname: barman
        privileged: true
        tty: true
        ports:
          - "5432"
        volumes:
          - ".:/docker"
          - "${BARMAN_SOURCE}:/barman"
        entrypoint: "/docker/entrypoint.sh"
        networks:
            public:
                ipv4_address: 10.111.211.11
networks:
    public:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.211.1/24
