uid            = root
gid            = root
use chroot     = no
max connections = 10
log file       = /var/log/rsyncd.log
pid file       = /var/run/rsyncd.pid

[archive]
    path        = /archive
    comment     = PostgreSQL WAL Archive
    read only   = yes
    list        = yes
