services:
  pg1:
    image: rockylinux9/postgres:15
    container_name: pg1
    hostname: pg1
    environment:
      - PGMAJOR=15
    volumes:
      - ./:/docker
    entrypoint: /docker/entrypoint.sh
  pg2:
    image: rockylinux9/postgres:15
    container_name: pg2
    hostname: pg2
    environment:
      - PGMAJOR=15
    volumes:
      - ./:/docker
    entrypoint: /docker/entrypoint.sh
