services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql_data/:/docker-entrypoint-initdb.d

  pg:
    image: pg_demo:fdw
    build: .
    container_name: pg
    hostname: pg
    environment:
      - PGMAJOR=13
    volumes:
      - ./:/docker
    entrypoint: /docker/entrypoint.sh
