services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql_data/:/docker-entrypoint-initdb.d

  pg:
    image: pg_demo:fdw
    build: .
    container_name: pg
    hostname: pg
    restart: always
    environment:
      - PGMAJOR=17
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./:/docker
      - ./init_scripts:/docker-entrypoint-initdb.d
