-- USE THIS AT YOUR OWN RISK.  Run pg_catcheck afterwards to make sure catalog isn't broken

-- SET allow_system_table_mods = on;
\set oldoid 0000
\set newoid 4218982467

-- List of attnames generated by looking for 'check_class_*' in pg_catcheck/definitions.c
-- List of commands generated by SELECT 'UPDATE ' || c.relname || ' SET ' || attname || '=:newoid WHERE ' || attname || '=:oldoid::oid;' FROM pg_attribute a join pg_class c on c.oid=a.attrelid WHERE attname in ('reltoastrelid', 'typrelid', 'indrelid', 'conrelid', 'confrelid', 'extconfig', 'tgrelid', 'tgconstrrelid', 'ftrelid', 'ev_class', 'inhrelid', 'inhparent', 'attrelid', 'starelid', 'adrelid', 'pdefrel', 'partrelid', 'policyobject', 'polrelid', 'qtrelid', 'aqrelid', 'classoid', 'partrelid', 'partdefid', 'prrelid', 'seqrelid', 'stxrelid', 'srrelid', 'rdrelid', 'rdrelid') AND relkind = 'r';

BEGIN;
UPDATE pg_class SET oid=:newoid WHERE oid=:oldoid::oid;
UPDATE pg_statistic SET starelid=:newoid WHERE starelid=:oldoid::oid;
UPDATE pg_type SET typrelid=:newoid WHERE typrelid=:oldoid::oid;
UPDATE pg_attribute SET attrelid=:newoid WHERE attrelid=:oldoid::oid;
UPDATE pg_class SET reltoastrelid=:newoid WHERE reltoastrelid=:oldoid::oid;
UPDATE pg_attrdef SET adrelid=:newoid WHERE adrelid=:oldoid::oid;
UPDATE pg_constraint SET confrelid=:newoid WHERE confrelid=:oldoid::oid;
UPDATE pg_constraint SET conrelid=:newoid WHERE conrelid=:oldoid::oid;
UPDATE pg_inherits SET inhparent=:newoid WHERE inhparent=:oldoid::oid;
UPDATE pg_inherits SET inhrelid=:newoid WHERE inhrelid=:oldoid::oid;
UPDATE pg_index SET indrelid=:newoid WHERE indrelid=:oldoid::oid;
UPDATE pg_statistic_ext SET stxrelid=:newoid WHERE stxrelid=:oldoid::oid;
UPDATE pg_rewrite SET ev_class=:newoid WHERE ev_class=:oldoid::oid;
UPDATE pg_trigger SET tgconstrrelid=:newoid WHERE tgconstrrelid=:oldoid::oid;
UPDATE pg_trigger SET tgrelid=:newoid WHERE tgrelid=:oldoid::oid;
UPDATE pg_description SET classoid=:newoid WHERE classoid=:oldoid::oid;
UPDATE pg_shdescription SET classoid=:newoid WHERE classoid=:oldoid::oid;
UPDATE pg_foreign_table SET ftrelid=:newoid WHERE ftrelid=:oldoid::oid;
UPDATE pg_policy SET polrelid=:newoid WHERE polrelid=:oldoid::oid;
UPDATE pg_init_privs SET classoid=:newoid WHERE classoid=:oldoid::oid;
UPDATE pg_seclabel SET classoid=:newoid WHERE classoid=:oldoid::oid;
UPDATE pg_shseclabel SET classoid=:newoid WHERE classoid=:oldoid::oid;
UPDATE pg_partitioned_table SET partdefid=:newoid WHERE partdefid=:oldoid::oid;
UPDATE pg_partitioned_table SET partrelid=:newoid WHERE partrelid=:oldoid::oid;
UPDATE pg_sequence SET seqrelid=:newoid WHERE seqrelid=:oldoid::oid;
UPDATE pg_publication_rel SET prrelid=:newoid WHERE prrelid=:oldoid::oid;
UPDATE pg_subscription_rel SET srrelid=:newoid WHERE srrelid=:oldoid::oid;
UPDATE edb_policy SET policyobject=:newoid WHERE policyobject=:oldoid::oid;
UPDATE edb_redaction_column SET rdrelid=:newoid WHERE rdrelid=:oldoid::oid;
UPDATE edb_redaction_policy SET rdrelid=:newoid WHERE rdrelid=:oldoid::oid;
UPDATE edb_queue_table SET qtrelid=:newoid WHERE qtrelid=:oldoid::oid;
UPDATE edb_queue SET aqrelid=:newoid WHERE aqrelid=:oldoid::oid;
COMMIT;
