version: '3'
services:
  master:
    build: .
    image: efmpgpool:latest
    container_name: master
    hostname: master
    privileged: true
    volumes:
      - ./:/docker
      - ./:/tmp/efm-scripts
    networks:
      app_net:
        ipv4_address: 172.22.77.50
  slave1:
    image: efmpgpool:latest
    container_name: slave1
    hostname: slave1
    privileged: true
    volumes:
      - ./:/docker
      - ./:/tmp/efm-scripts
    networks:
      app_net:
        ipv4_address: 172.22.77.51
  slave2:
    image: efmpgpool:latest
    container_name: slave2
    hostname: slave2
    privileged: true
    volumes:
      - ./:/docker
      - ./:/tmp/efm-scripts
    networks:
      app_net:
        ipv4_address: 172.22.77.52
  witness:
    image: efmpgpool:latest
    container_name: witness
    hostname: witness
    privileged: true
    volumes:
      - ./:/docker
      - ./:/tmp/efm-scripts
    networks:
      app_net:
        ipv4_address: 172.22.77.53
networks:
  app_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.22.77.0/24
