version: '3'
services:
  pg1:
    image: postgres-11:latest
    container_name: pg1
    hostname: pg1
    volumes:
      - /Users/richyen/Desktop/:/docker
  pg2:
    image: postgres-11:latest
    container_name: pg2
    hostname: pg2
    volumes:
      - /Users/richyen/Desktop/:/docker
