version: '3'
services:
  ldap-service:
    image: osixia/openldap:1.1.11
    container_name: ldap-service
    hostname: ldap-service
    ports:
      - "389:389"
      - "689:689"
    volumes:
      - ./certs:/container/service/slapd/assets/certs
      - ./ldif/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
      - .:/docker
    environment:
      - LDAP_TLS_VERIFY_CLIENT=try
      - LDAP_TLS_CRT_FILENAME=ldap_server.pem
      - LDAP_TLS_KEY_FILENAME=ldap_server.key
      - LDAP_TLS_CA_CRT_FILENAME=ldap_server.pem
    command: --copy-service
  console:
    image: osixia/phpldapadmin:0.7.2
    container_name: phpldapadmin-service
    hostname: phpldapadmin-service
    depends_on:
      - ldap-service
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-service
    ports:
      - "6443:443"
  database:
    image: centos7/postgres:10.10
    links:
      - ldap-service
    container_name: pg
    hostname: pg
    privileged: true
    entrypoint: /docker/entrypoint.sh
    ports:
      - "5432:5432"
    volumes:
      - .:/docker
