version: '3'
services:
  centos:
    image: centos:7
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    cap_add:
      - ALL
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "${HOME}:/docker"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    command: "/usr/sbin/init"
