version: '3'
services:
  centos:
    image: centos:7
    container_name: centos7
    hostname: centos7
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "${HOME}:/docker"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    command: "/usr/sbin/init"
