---
version: '3'
services:
    pg1:
        image: centos7/postgres-13:latest
        container_name: pg1
        hostname: pg1
        privileged: true
        tty: true
        ports:
          - "5432"
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup"
          - "./:/docker"
        command: "/usr/sbin/init"
        networks:
            public:
                ipv4_address: 10.111.220.11
    pg2:
        image: centos7/postgres-13:latest
        container_name: pg2
        hostname: pg2
        privileged: true
        tty: true
        ports:
          - "5432"
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup"
          - "./:/docker"
        command: "/usr/sbin/init"
        networks:
            public:
                ipv4_address: 10.111.220.12
networks:
    public:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.220.1/24
