uid             = root
gid             = root
use chroot      = no
max connections = 10
log file        = /var/log/rsyncd.log
pid file        = /var/run/rsyncd.pid

[archive]
    path        = /archive
    comment     = WAL Archive Relay
    read only   = yes
    list        = yes
